version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/ruby:3.3
    steps:
      - checkout
      - run:
          name: deploy
          command: '/bin/bash deploy.sh'
workflows:
  build:
    jobs:
     - deploy:
          filters:
            branches:
              only:
                - main
